### ISSUE TITLE
GCC 11 -Os breaks code

### ISSUE THREAD

**Issue by mocksoul** [ordian/pydirectio#3]
GCC 11 optimize code too much with default flags (`-Os`):

```
  x86_64-pc-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -fPIC -I/mnt/mfstest/venv/include -I/usr/include/python3.10 -c directiomodule.c -o build/temp.linux-x86_64-cpython-310/directiomodule.o
  x86_64-pc-linux-gnu-gcc -shared build/temp.linux-x86_64-cpython-310/directiomodule.o -L/usr/lib64 -o build/lib.linux-x86_64-cpython-310/directio.cpython-310-x86_64-linux-gnu.so
```

This leads to:

```
ImportError: /mnt/mfstest/venv/lib/python3.10/site-packages/directio.cpython-310-x86_64-linux-gnu.so: undefined symbol: aligned_allocate
```

`-O1` or `-O2` fixes problem:

```
  x86_64-pc-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -fPIC -I/mnt/mfstest/venv/include -I/usr/include/python3.10 -c directiomodule.c -o build/temp.linux-x86_64-cpython-310/directiomodule.o
  x86_64-pc-linux-gnu-gcc -shared -O2 build/temp.linux-x86_64-cpython-310/directiomodule.o -L/usr/lib64 -o build/lib.linux-x86_64-cpython-310/directio.cpython-310-x86_64-linux-gnu.so
```

Everything is good:

```
./venv/bin/python -c 'import directio; print(directio.__version__)'
1.2
```

GCC info:

```
home /mnt/mfstest # gcc --version
gcc (Gentoo 11.3.0 p4) 11.3.0
```

p.s.
And another bug spotted here: `__version__` not updated for 1.3 :)

**Comment by ordian** [comment]
Thanks for the report!

Do you think this is a problem with gcc specifically? Or a bug due to incorrect `__version__`?

> And another bug spotted here: __version__ not updated for 1.3 :)

My bad, should be easy to fix. :)

**Comment by mocksoul** [comment]
> Do you think this is a problem with gcc specifically?

I think that can be fixed by declaring some pointers as volatile to avoid unnecessary optimizations.

**Comment by ordian** [comment]
> GCC 11 optimize code too much with default flags (-Os):

You meant `-O0`, which doesn't optimize. 

I found the culprit, it seems to be `inline` keyword on functions. Will submit a PR to fix this, thanks!

**Comment by mocksoul** [comment]
> You meant -O0, which doesn't optimize.

No, I meant `-Os`, optimize for `size`. This is default in never gcc's I guess. At least it is default on my system :).
Thnx for fix!

**Comment by ordian** [comment]
Could you confirm #4 fixes it for you?

**Comment by mocksoul** [comment]
Yes, it works.
1.2 stuck version is also fixed ^_^
